#!/usr/bin/env python3
"""Create the ESP32 HTTPS certificate-bundle header used by the firmware."""

from __future__ import annotations

import argparse
import sys
import urllib.parse
import urllib.request
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
DEFAULT_HEADER = SCRIPT_DIR.parent / "firmware" / "x509_crt_bundle.h"
MAX_DOWNLOAD_BYTES = 5 * 1024 * 1024
DEFAULT_CERT_BUNDLE_MAX_CERTS = 200
DEFAULT_CA_URL = "https://raw.githubusercontent.com/espressif/esp-idf/master/components/mbedtls/esp_crt_bundle/cacrt_all.pem"


def download_ca(url: str, destination: Path) -> Path:
    parsed = urllib.parse.urlparse(url)
    if parsed.scheme != "https" or not parsed.netloc:
        raise ValueError("--ca-url must be a complete HTTPS URL")

    try:
        with urllib.request.urlopen(url, timeout=30) as response:
            data = response.read(MAX_DOWNLOAD_BYTES + 1)
    except OSError as error:
        raise RuntimeError(f"Unable to download CA certificate: {error}") from error

    if len(data) > MAX_DOWNLOAD_BYTES:
        raise ValueError("Downloaded CA file exceeds the 5 MiB safety limit")

    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_bytes(data)
    return destination


def write_header(bundle: bytes, destination: Path) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "// Generated by arduino/certs/make_cert_bundle.py. Do not edit.",
        "#pragma once",
        "#include <Arduino.h>",
        "",
        f"const size_t x509_crt_bundle_len = {len(bundle)};",
        "const uint8_t x509_crt_bundle[] PROGMEM = {",
    ]
    for offset in range(0, len(bundle), 16):
        values = ", ".join(f"0x{byte:02X}" for byte in bundle[offset : offset + 16])
        lines.append(f"  {values},")
    lines.extend(["};", ""])
    destination.write_text("\n".join(lines), encoding="ascii")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build the x509_crt_bundle.h required by the photo-frame firmware."
    )
    source = parser.add_mutually_exclusive_group()
    source.add_argument("--ca-file", type=Path, help="Local PEM or DER root-CA file")
    source.add_argument("--ca-url", help="HTTPS URL of a PEM or DER root-CA file")
    parser.add_argument(
        "--download-to",
        type=Path,
        help="Where to save a CA downloaded with --ca-url (default: arduino/certs/downloaded_ca.pem)",
    )
    parser.add_argument("--output", type=Path, default=DEFAULT_HEADER, help=f"Header path (default: {DEFAULT_HEADER})")
    parser.add_argument("--max-certs", type=int, default=DEFAULT_CERT_BUNDLE_MAX_CERTS)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.ca_file:
        source = args.ca_file.resolve()
        if not source.is_file():
            raise ValueError(f"CA file does not exist: {source}")
    else:
        destination = args.download_to or SCRIPT_DIR / "downloaded_ca.pem"
        url = args.ca_url or DEFAULT_CA_URL
        source = download_ca(url, destination.resolve())
        print(f"Downloaded CA certificate to {source}")

    try:
        from gen_crt_bundle import CertificateBundle
    except ModuleNotFoundError as error:
        if error.name != "cryptography":
            raise
        raise RuntimeError(
            "Missing Python dependency 'cryptography'. Install it with: python3 -m pip install cryptography"
        ) from error

    certificates = CertificateBundle()
    certificates.add_from_file(str(source))
    bundle = certificates.create_bundle(args.max_certs)
    output = args.output.resolve()
    write_header(bundle, output)
    print(f"Wrote {len(bundle)}-byte certificate bundle to {output}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, RuntimeError, ValueError) as error:
        print(f"error: {error}", file=sys.stderr)
        raise SystemExit(2)
